config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "ihm#homepage"
  
  devise_for :users, controllers: {sessions: 'sessions'}

  devise_scope :user do
    post "sessions/login"
  end
  
  namespace :admin do
        get '/dashboard' , to: 'admins#admin_dashboard'
  end

  resources :packages 
  resources :stripe_accounts

  post 'packages/create_package'
  post 'packages/export_package'

  get 'payments/payment'
  get 'ihm/dashboard'
  post 'ihm/perform_job'
  get 'ihm/child_dash'
  get 'user/new_user'
  get 'user/locked_user'
  get 'user/edit_profile'
  get 'user/register_family'
  get 'user/add_family_members'
  post 'user/delete_member'
  post 'user/do_family_register'
  post 'user/do_add_family_members'
  get 'user/view_member'
  post 'user/do_edit_profile'
  post 'user/create_new_user'
  delete 'user/delete_user'
  post 'user/signup'
  post 'user/do_activate_account'
  post 'user/regenerate_active_token'
  get 'user/activate_account'
  get 'user/verified_users'
  get 'user/view_user'
  get 'user/unapproved_users'
  get 'user/unpaid_users'
  post 'user/send_regenerate_active_token_email'
  get 'user/all_family_members'


get 'tasks/new'
post 'tasks/create'
get 'tasks/user_schedule'
post 'tasks/user_tasks'
get 'tasks/edit_task'
post 'tasks/do_edit_task'
post 'tasks/delete_task'


  post 'payments/create_payment'

  get 'payments_track/all_payments'
  get 'payments_track/up_coming_payments'
  post 'payments_track/send_payment_reminder'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  # devise_for :users, controllers: {
  #       sessions: 'users/sessions' do
  #         post 'login/users/sessions'
  #       end
  #     }
end

app/models/task.rb
class Task < ApplicationRecord
belongs_to :user , optional: true
belongs_to :family_member , optional: true

enum task_type: ["today" , "schedule" , "previous" , "complete" , "incomplete" , "pending" , "assigned"]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :task_validations , :only => [:create , :do_edit_task]
    before_action :update_tasks_type , only: :new

    def new
       @task = Task.new
       @members = FamilyMember.all.where(family_id: current_user.family.id).joins(:family) if current_user.parent_id == 0
    end

    def create
      @task = Task.new
      if @dead_day >= @current_day
        if current_user.parent_id == 0
            if params[:task]["member_id"].present?
              @task = Task.new(task_name: params[:task]["task_name"], task_desc: params[:task]["task_desc"], dead_time: params[:task]["dead_time"], dead_day: @dead_day,  member_id: params[:task]["member_id"] , assigned_by: current_user.email , task_type: @task_type )
            else
              @task = Task.new(task_name: params[:task]["task_name"], task_desc: params[:task]["task_desc"] ,dead_time: params[:task]["dead_time"], dead_day: @dead_day, user_id: current_user.id , task_type: @task_type)
            end
              if @task.save 
                  flash.notice = "Task Created Successfully"
                  redirect_to tasks_new_path
              end
          else 
                  @member_id = FamilyMember.find_by_email(current_user.email).id
                  @task = Task.new(task_name: params[:task]["task_name"], task_desc: params[:task]["task_desc"], dead_time: params[:task]["dead_time"], dead_day: @dead_day, member_id: @member_id , task_type: @task_type)
                  if @task.save 
                    flash.notice = "Task Created Successfully"
                    redirect_to tasks_new_path
                  end
          end
        else
          flash.alert = "You can not create task on Previous Days. Please create for today or for next days"
          redirect_to tasks_new_path
        end
    end #create_end

    def user_tasks
      if current_user.parent_id == 0
         @tasks = current_user.tasks.where(task_type: params[:type])
      else
        @member = FamilyMember.find_by_email(current_user.email)
        @tasks  = Task.all.where(task_type: params[:type]).where(member_id: @member.id)
      end
      respond_to do |format|
          format.js {@tasks }
          format.html
      end
    end

    def user_schedule #list members Task
      @tasks = Task.all.where(member_id: params[:id])
    end

    def edit_task
      @task = Task.find(params[:id])
      @members = current_user.family.family_members if current_user.family.present? 
    end

    def do_edit_task
      @task = Task.find(params[:id])
      if @dead_day >= @current_day
        if params[:task]["member_id"].present?
          @memberTask = Task.new(task_name: params[:task]["task_name"], task_desc: params[:task]["task_desc"], dead_time: params[:task]["dead_time"], dead_day: @dead_day,  member_id: params[:task]["member_id"] , assigned_by: current_user.email , task_type: @task_type )
          if @memberTask.save
             @task.destroy
             flash.notice = "Task update Successfully!"
             redirect_to tasks_new_path
          end
        else
          @task.update(task_name: params[:task]["task_name"], task_desc: params[:task]["task_desc"] ,dead_time: params[:task]["dead_time"], dead_day: @dead_day, task_type: @task_type)
          flash.notice = "Task update Successfully!"
          redirect_to tasks_new_path
        end

      else
        flash.alert = "You can not edit task on Previous Days. Please create for today or for next days"
        redirect_to tasks_edit_task_path
      end

    end #do_edit_task_end

    def delete_task
      @task = Task.find(params[:id])
      delete = @task.destroy ? true : false if @task.present?
      if delete
        flash.notice = "Delete Successfully"
        redirect_to tasks_new_path
      else
        flash.alert = "Please try again!"
        redirect_to tasks_new_path
      end
    end

    private
    def task_validations
        @dead_day =  params[:task][:dead_day].present? ? params[:task][:dead_day] : Time.now.strftime("%Y-%m-%d")
        @task_type = @dead_day == Time.now.strftime("%Y-%m-%d") ? 0 : 1
        @current_day = Time.now.strftime("%Y-%m-%d")
        @previous_day = Time.now.prev_day
        @next_day = Time.now.next_day 
    end

    def update_tasks_type
      if current_user.parent_id == 0
         @tasks = current_user.tasks
      else
        @member = FamilyMember.find_by_email(current_user.email)
        @tasks = Task.all.where(member_id: @member.id)
      end

      @current_day = Time.now.strftime("%Y-%m-%d")
      @tasks.each do |t|
          if t.dead_day < @current_day
             t.previous!
          elsif t.schedule? && t.dead_day == @current_day
             t.today!
          end
      end
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_usertasks.html.erb
<table class="ui compact celled definition table">
  <thead>
    <tr>
      
      <th>Task Name</th>
      <th>Description</th>
      <th>Dead Day</th>
      <th>Dead Time</th>
     <% if current_user.parent_id != 0 %>
      <th>Assigned By</th>
     <% end %>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>

  <% @tasks&.each do |p| %>
    <tr>
      <td class="collapsing">
      <%= p.task_name %>
      </td>
      <td><%=p.task_desc%></td>
      <td><%=p.dead_day%></td>
      <td><%=p.dead_time%></td>
      <% if current_user.parent_id != 0 %>
      <td><%=p.assigned_by%></td>
     <% end %>
    <td> 
      <%= link_to_if (!p.assigned_by.present?) , "Edit" , tasks_edit_task_path(:id => p.id) do %>
        <p class="link_center"><i class="window minimize red icon"></i></p>
      <% end %> 
    </td>
    <td> 
    <% if !p.assigned_by.present? %>
    <%= button_to "Delete" , tasks_delete_task_path(:id => p.id) , form: {data: {turbo_confirm: 'Delete this task?'}} %>
    <% else %>
    <p class="link_center"><i class="window minimize red icon"></i></p>
    <% end %> 
  </td>
    </tr>
    <% end %>

    </tbody>
  <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <div class="ui small button">
          <%= link_to "Back" , :back %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>


<script>
$(document).ready(function(){
  $(".do_not_go").click(function(e){
    e.preventDefault();
  })
})
</script>

app/views/tasks/edit_task.html.erb
<div class="ui container">

<div class="link_center">
<h1>Edit Task </h1>
</div>
<% @task.dead_time%>
<div class="add_member">
<div class="ui form">
<%= form_for(@task , url: tasks_do_edit_task_path(id: @task.id), method: :POST) do |f| %>
 
    <div class="field">
    Name: <%= f.text_field :task_name %><br>
    </div>
    <div class="field">
    Description: <%= f.text_area :task_desc %><br>
    </div>
    <div class="field">
    Time: <%= f.time_field :dead_time , :value => @task.dead_time%><br>
    </div>
    <div class="field">
    Day: <%= f.date_field :dead_day , :value => @task.dead_day%><br>
    </div>

    <% if current_user.parent_id == 0 %>
    <div class="field">
    Assign_to: <%= f.select :member_id , @members&.collect { |m| [m.email, m.id] } , :include_blank => true %>
    </div>
    <% end %>
<br>
    <%= f.submit "Update" , class:"ui primary button" %>
<% end %>


</div>
</div>

</div>

app/views/tasks/new.html.erb
<br><br><br><br><br>
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">



<p class="link_center click_to_add"><button class="ui button">Add New Task</button></p>
<div class="add_member">
<div class="ui form">
<%= form_for(@task , url: tasks_create_path , method: :post) do |p| %>
  <div class="field">
    <label>Name</label>
    <%= p.text_field :task_name , placeholder: "Enter member name"%>
  </div>

  <div class="field">
    <label>Description</label>
    <%= p.text_area :task_desc , placeholder: "Enter user email" , :required => true%>
  </div>


  <label>Select Time</label>
   
  <%= p.time_field  :dead_time , {ampm: true}%>
<br>
  <label>Select Day</label>
  <%= p.date_field :dead_day  %>
<br>
<% if current_user.parent_id == 0 %>
  <div class="field">
    <label>Assign_to</label>
    <%= p.select :member_id , @members.collect { |m| [m.email, m.id] } , :include_blank => true %>
  </div>
<% end %>

<%= p.submit "Create" , class:"ui button blue"%>
<% end %>

<br>
<%= link_to "Back" , :back %>
</div>
<hr>
</div>
</div>
</div>
</div>
</div>
</div>
</div>



<div class="ui container">
<br><br><br>

<br><br><br><br>
<div class="link_right">

</div>



<div class="link_center">
<div class="ui labeled button" tabindex="0">
  <div class="ui black button">
    <i class="calendar check icon"></i> <strong class="today">Today Tasks</strong> 
  </div>
  <a class="ui basic black left pointing label">
  <strong class="schedule">Schedule Tasks</strong>
  </a>
  <a class="ui basic black left pointing label">
  <strong class="previous">Previous Tasks</strong>
  </a>
</div>
</div>
<br><br>
<div class="user_tasks"> </div>

</div>


<script>

$(document).ready(function(){
    $(".add_member").hide();
    $("#today").hide();
    $(".click_to_add").click(function(){
        $(".add_member").slideToggle();
    })
   
    // Fetch Today Tasks thruogh Ajax call
    $(".today").click(function(){
      send_data = {type: "today"}
      $.ajax({
        type: 'POST',
        url: '/tasks/user_tasks',
        beforeSend: function(xhr) {xhr.setRequestHeader("X-CSRF-Token", $("meta[name='csrf-token']").attr("content"))},
        data: send_data,
        dataType: 'script',
        success: function(data) {
        console.log("okay")
        }
      });

    })


    // Fetch Schedule Tasks thruogh Ajax call
    $(".schedule").click(function(){
      send_data = {type: "schedule"}
      $.ajax({
        type: 'POST',
        url: '/tasks/user_tasks',
        beforeSend: function(xhr) {xhr.setRequestHeader("X-CSRF-Token", $("meta[name='csrf-token']").attr("content"))},
        data: send_data,
        dataType: 'script',
        success: function(data) {
        console.log("okay")
        }
      });

    })


    // Fetch previous Tasks thruogh Ajax call
    $(".previous").click(function(){
      send_data = {type: "previous"}
      $.ajax({
        type: 'POST',
        url: '/tasks/user_tasks',
        beforeSend: function(xhr) {xhr.setRequestHeader("X-CSRF-Token", $("meta[name='csrf-token']").attr("content"))},
        data: send_data,
        dataType: 'script',
        success: function(data) {
        console.log("okay")
        }
      });

    })
})
</script>

app/views/tasks/user_schedule.html.erb
<div class="ui container">



<div class="link_center"><strong>Schedule Tasks</strong></div>
<table class="ui compact celled definition table">
  <thead>
    <tr>
      
      <th>Task Name</th>
      <th>Description</th>
      <th>Dead Day</th>
      <th>Dead Time</th>
      <th>Assigned by</th>
      <th>Status</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>

  <% @tasks&.each do |p| %>
    <tr>
      <td class="collapsing">
      <%= p.task_name %>
      </td>
      <td><%=p.task_desc%></td>
      <td><%=p.dead_day%></td>
      <td><%=p.dead_time%></td>
      <td><%= p.assigned_by %></td>
      <td><%=p.status%></td>
      <% if p.assigned_by == current_user.email %>
      <td>Edit</td>
      <td>Delete</td>
      <% end %>
    </tr>
    <% end %>

    </tbody>

</div>

app/views/tasks/user_tasks.js.erb
$(".user_tasks").html("<%= j render :partial => 'tasks/usertasks' %>");	