config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "ihm#homepage"
  
  devise_for :users, controllers: {sessions: 'sessions'}

  devise_scope :user do
    post "sessions/login"
  end
  
  namespace :admin do
        get '/dashboard' , to: 'admins#admin_dashboard'
  end

  resources :packages 
  resources :stripe_accounts

  post 'packages/create_package'
  post 'packages/export_package'

  get 'payments/payment'
  get 'ihm/dashboard'
  post 'ihm/perform_job'
  get 'ihm/child_dash'
  get 'user/new_user'
  get 'user/locked_user'
  get 'user/edit_profile'
  get 'user/register_family'
  get 'user/add_family_members'
  post 'user/delete_member'
  post 'user/do_family_register'
  post 'user/do_add_family_members'
  get 'user/view_member'
  post 'user/do_edit_profile'
  post 'user/create_new_user'
  delete 'user/delete_user'
  post 'user/signup'
  post 'user/do_activate_account'
  post 'user/regenerate_active_token'
  get 'user/activate_account'
  get 'user/verified_users'
  get 'user/view_user'
  get 'user/unapproved_users'
  get 'user/unpaid_users'
  post 'user/send_regenerate_active_token_email'
  get 'user/all_family_members'


get 'tasks/new'
post 'tasks/create'
get 'tasks/user_schedule'
post 'tasks/user_tasks'
get 'tasks/edit_task'
post 'tasks/do_edit_task'
post 'tasks/delete_task'


  post 'payments/create_payment'

  get 'payments_track/all_payments'
  get 'payments_track/up_coming_payments'
  post 'payments_track/send_payment_reminder'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  # devise_for :users, controllers: {
  #       sessions: 'users/sessions' do
  #         post 'login/users/sessions'
  #       end
  #     }
end

app/models/stripe_account.rb
class StripeAccount < ApplicationRecord
end

app/controllers/stripe_accounts_controller.rb
class StripeAccountsController < ApplicationController
    before_action :authenticate_user!

    def new
        @stripe = StripeAccount.new
    end
    
    def create
        @stripe = StripeAccount.new(email: params[:stripe_account]["email"],
                                    p_key: params[:stripe_account]["p_key"],
                                    s_key: params[:stripe_account]["s_key"])
        if @stripe.save
            flash.notice = "Successfully account created!"
            redirect_to stripe_accounts_path
        else
            flash.alert = "Error try again!"
            render 'new'
        end
    end

    def edit
        @stripe = StripeAccount.find(params[:id])
    end

    def update
        @stripe = StripeAccount.find(params[:id])
        if @stripe.present?
          if @stripe.update(email: params[:stripe_account]["email"],
                           p_key: params[:stripe_account]["p_key"],
                           s_key: params[:stripe_account]["s_key"])

            flash.notice = "Successfully account updated!"
            redirect_to stripe_accounts_path
          else
            flash.alert = "Error try again!"
            render 'edit'
          end
        end
    end

    def index
        @stripeAccounts = StripeAccount.all
    end

    def destroy
        @stripe = StripeAccount.find(params[:id])
        if @stripe.destroy
            flash.notice = "Successfully account deleted!"
            redirect_to stripe_accounts_path
        end
    end
end

app/views/stripe_accounts/edit.html.erb
<br><br><br><br><br>

<div class="ui container">
<p class="link_center"><strong>Edit Stripe Account</strong></p>
<div class="ui form">
<%= form_for(@stripe) do |p| %>
    <div class="field">
      <label>Email</label>
      <%= p.text_field :email , placeholder: "Enter Stripe email"%>
    </div>
    <div class="field">
      <label>Published key</label>
      <%= p.text_field :p_key , placeholder: "Enter stripe published key"%>
    </div>
    <div class="field">
    <label>Secret key</label>
    <%= p.text_field :s_key , placeholder: "Enter stripe secret key"%>
  </div>
  <%= p.submit "Update " , class:"ui button blue"%>
  <% end %>

<br>
<%= link_to "Back" , :back %>
</div>

</div>

app/views/stripe_accounts/index.html.erb
<div class="ui container">
<br><br><br>
<div class="link_center"><strong>All Stripe Accounts</strong></div>
<table class="ui compact celled definition table">
  <thead>
    <tr>
      <th>Active</th>
      <th>Email</th>
      <th>Published key</th>
      <th>Secret key</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
  <% @stripeAccounts.each do |p| %>
    <tr>
      <td class="collapsing">
      <% if p.status == 1 %>
        <div class="link_center">   <i class="icon check green"></i> </div>
        <% else %>
        <div class="link_center"> <i class="icon x icon red"></i></div>
        <% end %>
      </td>
      <td><%=p.email%></td>
      <td class="pk"><%=p.p_key%></td>
      <td class="pk2"><u>Show key</u></td>
      <td class="sk"><%=p.s_key%></td>
      <td class="sk2"><u>Show key</u></td>
      <td>
         <div class="inline"><%= link_to "Edit" , edit_stripe_account_path(p.id) %> 
      </td>
      <td>
         <%= button_to "Delete" , stripe_account_path(p.id) , method: :delete , class:"delete" %></div>
      </td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <div class="ui right floated small labeled icon button">
          <i class="user icon"></i> <%= link_to "Add new account" , new_package_path %>
        </div>
        <div class="ui small button">
          <%= link_to "Back" , :back %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>
</div>


<script>

</script>

app/views/stripe_accounts/new.html.erb
<br><br><br><br><br>
<div class="ui container">
<p class="link_center"><strong>New Stripe Account</strong></p>
<div class="ui form">
<%= form_for(@stripe) do |p| %>
  <div class="field">
    <label>Email</label>
    <%= p.text_field :email , placeholder: "Enter Stripe email"%>
  </div>
  <div class="field">
    <label>Published key</label>
    <%= p.text_field :p_key , placeholder: "Enter stripe published key"%>
  </div>
  <div class="field">
  <label>Secret key</label>
  <%= p.text_field :s_key , placeholder: "Enter stripe secret key"%>
</div>
<%= p.submit "Create " , class:"ui button blue"%>
<% end %>

<br>
<%= link_to "Back" , :back %>
</div>

</div>