config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "ihm#homepage"
  
  devise_for :users, controllers: {sessions: 'sessions'}

  devise_scope :user do
    post "sessions/login"
  end
  
  namespace :admin do
        get '/dashboard' , to: 'admins#admin_dashboard'
  end

  resources :packages 
  resources :stripe_accounts

  post 'packages/create_package'
  post 'packages/export_package'

  get 'payments/payment'
  get 'ihm/dashboard'
  post 'ihm/perform_job'
  get 'ihm/child_dash'
  get 'user/new_user'
  get 'user/locked_user'
  get 'user/edit_profile'
  get 'user/register_family'
  get 'user/add_family_members'
  post 'user/delete_member'
  post 'user/do_family_register'
  post 'user/do_add_family_members'
  get 'user/view_member'
  post 'user/do_edit_profile'
  post 'user/create_new_user'
  delete 'user/delete_user'
  post 'user/signup'
  post 'user/do_activate_account'
  post 'user/regenerate_active_token'
  get 'user/activate_account'
  get 'user/verified_users'
  get 'user/view_user'
  get 'user/unapproved_users'
  get 'user/unpaid_users'
  post 'user/send_regenerate_active_token_email'
  get 'user/all_family_members'


get 'tasks/new'
post 'tasks/create'
get 'tasks/user_schedule'
post 'tasks/user_tasks'
get 'tasks/edit_task'
post 'tasks/do_edit_task'
post 'tasks/delete_task'


  post 'payments/create_payment'

  get 'payments_track/all_payments'
  get 'payments_track/up_coming_payments'
  post 'payments_track/send_payment_reminder'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  # devise_for :users, controllers: {
  #       sessions: 'users/sessions' do
  #         post 'login/users/sessions'
  #       end
  #     }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :confirm_password , :new_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
# Associations
  has_many :payments , dependent: :destroy
  has_many :user_packages , dependent: :destroy
  has_one :lockable , dependent: :destroy
  has_one :family , dependent: :destroy
  has_many :tasks , dependent: :destroy
  # has_one :stripe_accounts , dependent: :destroy
# Validations
validates :email, uniqueness: true

  # UpdatePayment.perform_now

  def full_name
    if first_name.present? && last_name.present?
      first_name + " " + last_name
    end
  end

  def package_name
    if user_packages.present?
     user_payment = user_packages.last
     package_detail = Package.find(user_payment.package_id)
     package_detail.name
    else
      return "User has no package"
    end
  end

  def user_price_paid
    if user_packages.present?
      user_payment = user_packages.last
      package_detail = Package.find(user_payment.package_id)
      "#{package_detail.price}" + "$"
     else
       return "User has no package"
     end
  end

  def contacts_allowed
    if user_packages.present?
      user_payment = user_packages.last
      package_detail = Package.find(user_payment.package_id)
      package_detail.contacts_allowed
     else
       return "User has no package"
     end
  end

  def age
     return  "#{Time.now.strftime("%Y").to_i - dateofbirth.to_i} "+"years"
  end

  def days_left
     valid_till = payment_date.to_i + 30
     days_left = valid_till - Time.now.strftime("%d").to_i
     if days_left < 5
      return "Please do your payment, After #{days_left} days your account will be locked"
      else
      return "#{days_left}" + " days left" 
    end
  end

  def active_contacts(user)
    if user.family.present?
    return FamilyMember.where(family_id: user.family.id).joins(:family).count
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["active_token", "admin", "country", "created_at", "dateofbirth", "email", "encrypted_password", "first_name", "gender", "id", "last_name", "parent_id", "payment", "payment_date", "remember_created_at", "reset_password_sent_at", "reset_password_token", "status", "updated_at"]
  end

  def self.allowed_members(user)
    @user = user
    pkg_id = UserPackage.find_by(user_id: @user.id).package_id
    return Package.find(pkg_id).contacts_allowed
  end

  def self.no_of_family_members(user)
     FamilyMember.all.where(family_id: user.family.id).count
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user! , except: [:signup, :activate_account, :do_activate_account, :regenerate_active_token]

  require 'securerandom'

  def new_user #get
      @user = User.new()
      @approved = User.all.where(status: 1).count
      @notapproved = User.all.where(status: 0).count
      @notpaid = User.all.where(payment: 0).count
      @paid = User.all.where(payment: 1).count
      @all = User.paginate(:page => params[:page], :per_page => 10)
      @q = @all.ransack(params[:q])
      @all_users = @q.result(distinct: true)
  end

  def create_new_user #post
    password = random_string = SecureRandom.hex(6)
    @user = User.new(email: params[:user]["email"], password: password)
    if @user.save
      UserMailer.add_user(@user, password).deliver_later
      flash.notice = "USer created Successfully!"
      redirect_to user_create_new_user_path
    else
      flash.alert = "Try again!"
      render 'new_user'
    end
  end

  def signup #post
    @user = User.find_by_email(params[:user]["email"])
    if @user.present? 
    if @user.payment == 0 && @user.parent_id == 0
        flash[:alert] = "Users already registered, Please complete your payment!"
        redirect_to payments_payment_path(id: @user.id)
    elsif @user.status == 0 && @user.parent_id == 0
      flash[:alert] = "Users already registered and payment is already done, Please activate your account!"
      regenerate_token(@user.id)
    elsif @user.status == 1 && @user.payment == 1 
      flash[:notice] = "Your account is already setup, you can login now!"
      redirect_to new_user_session_path
    end
    else
      @user = User.new()
      param = params[:user]
      @user.first_name = param["first_name"]
      @user.last_name = param["last_name"]
      @user.email = param["email"]
      @user.password = param["password"]
      @user.gender = param["gender"]
      @user.country = param["country"]
      @user.dateofbirth = param["dateofbirth"]
      if @user.save
        flash[:notice] = "Step 1 Completed Successfully!"
        redirect_to payments_payment_path(id: @user.id)
      end
  end
  end


  def activate_account #get
    @error = 0
    @user = User.find(params[:id])
  end

  def do_activate_account #post
    @user = User.find(params[:user]["id"])
    if @user.status == 0
    if @user.active_token == params[:user]["active_token"]
      @user.update(status: 1)
      flash[:notice] = "Congratulations, your account is fully activated, you can login now!"
      redirect_to new_user_session_path
    else
      @error = 1
      flash.alert = "Secret key is invalid!"
      render 'activate_account'
    end
  else
      flash[:notice] = "Your Account is already Activated, you can login now"
      redirect_to new_user_session_path
  end
  end

  

  def regenerate_active_token
   @user = User.find(params[:id])

   if @user.status == 0
    random_string = SecureRandom.hex(8)
    @user.update(active_token: random_string)
    UserMailer.activate_account(@user,random_string).deliver_later
    flash.notice = "Your token is regenerated kindly check your email!"
    redirect_to user_activate_account_path(id: @user.id)
    else
      flash.alert = "Please try again!"
      redirect_to new_user_session_path
    end
  
  end

  def send_regenerate_active_token_email
    @user = User.find(params[:id])
 
    if @user.status == 0
     random_string = SecureRandom.hex(8)
     @user.update(active_token: random_string)
     UserMailer.send_activate_account(@user,random_string).deliver_later
     flash.notice = "Your token is regenerated kindly check your email!"
    #  redirect_to user_activate_account_path(id: @user.id)
     else
       flash.alert = "Please try again!"
       redirect_to new_user_session_path
     end
   
   end

  def verified_users
     @users = User.all.where(payment:1, status:1)
     respond_to do |format|
      format.xlsx {}
      format.html {}
     end
  end

  def view_user
     @user = User.find(params[:id])
  end

  def unapproved_users
    @users = User.all.where(status: 0)
  end

  def unpaid_users
    @users = User.all.where(payment: 0)
  end

  def delete_user
    @user = User.find(params[:id])
    if @user.payment == 1
      flash.alert = "This User is active with Payment, Can't be delete"
      redirect_to user_new_user_path 
    else

      if @user.destroy
        flash.notice = "Deleted Successfully"
        redirect_to user_new_user_path 
      else
        flash.alert = "try again!"
        redirect_to user_new_user_path
      end
    end
  end

  def delete_member
      @member = FamilyMember.find(params[:id])
      @user = User.find_by_email(@member.email)
      @member.status = 0
      if @member.save
        @user.destroy if @user.present?
        FamilyMember.all.where(status: 0).delete_all
        flash.notice = "Member deleted successfully!"
        redirect_to user_add_family_members_path
      else
        flash.alert = "Error: Try again!"
        redirect_to user_add_family_members_path
      end
  end

  def locked_user
     @users = User.joins(:lockable)
  end



  def edit_profile #get
    @user = current_user
  end

  def do_edit_profile #post
   if params[:user]["new_password"].present? && params[:user]["confirm_password"].present?
      if current_user.valid_password?(params[:user]["password"])
          if params[:user]["new_password"] == params[:user]["confirm_password"]
            current_user.update(password: params[:user]["new_password"])
            flash.alert = "Password update Successfully"
            redirect_to user_view_user_path(id: current_user.id)
          else
            flash.alert = "New password Not same. Try again!"
            redirect_to user_view_user_path(id: current_user.id)
          end
        else
          flash.alert = "Invalid old Password"
          redirect_to user_view_user_path(id: current_user.id)
        end
   else

   if current_user.update(first_name: params[:user]["first_name"] , last_name: params[:user][:last_name],
                         gender: params[:user]["gender"], country: params[:user]["country"], 
                         dateofbirth: params[:user]["dateofbirth"] , phone_no: params[:user]["phone_no"]
                         )
                         flash.notice = "Profile Updated Successfully!"
                         redirect_to user_view_user_path(id: current_user.id)
   else
    flash.alert = "Please try again!"
    render 'edit_profile'
   end
  end    
  end


  def register_family #get
    @family = Family.new
    if current_user.family.present?
       redirect_to user_add_family_members_path
    end
  end

  def do_family_register #post
      if Family.create(family_name: params[:family]["family_name"], no_of_members: params[:family]["no_of_members"], user_id: current_user.id)
        flash.notice = "Family registered Successfully"
        redirect_to user_add_family_members_path
      else
        flash.alert = "Error Try again!" 
        render 'register_family'
      end
  end
  def add_family_members
    # @members = FamilyMember.where(family_id: current_user.family.id , status: 1).joins(:family)
    @members = FamilyMember.all.where(family_id: current_user.family.id , status: 1)
  end

  def do_add_family_members
    if User.no_of_family_members(current_user) < User.allowed_members(current_user) 
      find_dup = User.find_by_email(params[:family_member]["email"])
      if !find_dup.present?
        if @member = FamilyMember.create(name: params[:family_member]["name"], email: params[:family_member]["email"],
                              gender: params[:family_member]["gender"], role: params[:family_member]["role"], alpha: params[:family_member][:alpha] ,
                              password: params[:family_member]["password"], family_id: current_user.family.id)
            User.create(first_name: @member.name, email: @member.email, gender: @member.gender, alpha: @member.alpha , password: @member.password, parent_id: current_user.id)
                              flash.notice = "#{@member.name} Add Successfully"
                              redirect_to user_add_family_members_path
        end
      else
        flash.alert = "Email already Registered"
        redirect_to user_add_family_members_path
      end
     
    else
      flash.alert = "Your members limit is full. upgrade your account to create more"
    end
  end




  def view_member
    @member = FamilyMember.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/activate_account.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular check icon green"></i>
  Activate Your Account
</h2>

<div class="set_step"> 
<div class="ui ordered steps ">
  <div class="completed step">
    <div class="content">
      <div class="title">Sign-up</div>
      <div class="description">Congratulations!</div>
    </div>
  </div>
  <div class="completed step">
    <div class="content">
      <div class="title">Billing</div>
      <div class="description">Congratulations!</div>
    </div>
  </div>
  <div class="active step">
    <div class="content">
      <div class="title">Account Activate</div>
      <div class="description">Verify your Account</div>
    </div>
  </div>
</div>
</div>

<br><br><br>
<div class="ui container">
<%= form_for(User.new, url: user_do_activate_account_path(@user)) do |f| %>
    <div class = "ui form">
    <div class = "two fields">
        <%= f.hidden_field :id , :value => @user.id%>
        <%= f.text_field :active_token , placeholder: "Enter your secret key"%>
    </div>
    <br><br><br><br><br><br>
    <div>
        <%= f.submit "Activate" , class:"ui blue submit button centered"%>
     
    </div>
    </div>

<% end %>
<% if @error > 0 %>
<%= button_to "Resend Token" , user_regenerate_active_token_path(id: @user.id)%>
<% end %>
</div>

app/views/user/add_family_members.html.erb
<br><br><br><br><br>
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">
<div class="ui container">



<p class="link_center click_to_add "><strong>Add New User</strong></p>
<div class="add_member">
<div class="ui form">
<%= form_for(FamilyMember.new , url: user_do_add_family_members_path , method: :post) do |p| %>
  <div class="field">
    <label>Name</label>
    <%= p.text_field :name , placeholder: "Enter member name"%>
  </div>

  <div class="field">
    <label>Email</label>
    <%= p.text_field :email , placeholder: "Enter user email" , :required => true%>
  </div>

  <div class="field">
    <label>Gender</label>
    <%= p.select :gender , ["male" , "female" , "other"]%>
  </div>

  <div class="field">
    <label>Role</label>
    <%= p.select :role , ["Wife" , "Husband" ,  "Son" , "Daughter"] , :include_blank => true , :required => true%>
  </div>

  <div class="field">
  <%= p.check_box :alpha %>  Alpha Member
  </div>

  <div class="field">
    <label>Password</label>
    <%= p.text_field :password , placeholder: "Enter Password" , :required => true%>
  </div>
<%= p.submit "Create" , class:"ui button blue"%>
<% end %>

<br>
<%= link_to "Back" , :back %>
</div>
<hr>
</div>
</div>
</div>
</div>
</div>
</div>
</div>



<div class="ui container">
<br><br><br>

<br><br><br><br>
<div class="link_right">

</div>

<div class="link_center"><strong>All Members</strong></div>
<table class="ui compact celled definition table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Gender</th>
      <th>Relation</th>
      <th>Alpha Member</th>
      <th>Show</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>

  <% @members&.each do |p| %>
    <tr>
      <td class="collapsing">
      <%= p.id %>
      </td>
      <td><%=p.name%></td>
      <td><%=p.email%></td>
      <td><%=p.gender%></td>
      <td><%=p.role%></td>
      <td><%=p.alpha%></td>
      <td>
         <div class="inline"><%= link_to "Show" , user_view_member_path(id: p.id) %> 
      </td>
      <td>
         <%= button_to "Delete" , user_delete_member_path(id: p.id) %></div>
      </td>
    </tr>
    <% end %>

    </tbody>
  <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <div class="ui small button">
          <%= link_to "Back" , :back %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>


</div>


<script>

$(document).ready(function(){
    $(".add_member").hide();
    $(".click_to_add").click(function(){
        $(".add_member").slideDown();
    })
})
</script>

app/views/user/all_family_members.html.erb
<div class="ui container">

<div class="link_center">
<h1> All Members </h1>
</div>
<table class="ui compact celled definition table">
<thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Relation</th>
    <th>Alpha Member</th>
    <th>Show</th>
    <th>Delete</th>
  </tr>
</thead>
<tbody>

<% @members&.each do |p| %>
  <tr>
    <td class="collapsing">
    <%= p.id %>
    </td>
    <td><%=p.name%></td>
    <td><%=p.email%></td>
    <td><%=p.gender%></td>
    <td><%=p.role%></td>
    <td><%=p.alpha%></td>
    <td>
       <div class="inline"><%= link_to "Show" , user_view_member_path(id: p.id) %> 
    </td>
    <td>
       <%= button_to "Delete" , user_delete_member_path(id: p.id) %></div>
    </td>
  </tr>
  <% end %>

  </tbody>
<tfoot class="full-width">
  <tr>
    <th></th>
    <th colspan="4">
      <div class="ui small button">
        <%= link_to "Back" , :back %>
      </div>
    </th>
  </tr>
</tfoot>
</table>
</div>

app/views/user/register_family.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="ui container">
	<div class="row">
    <div class="col-md-4">
		<div class="form_main">
                <h4 class="heading"><strong>Register </strong> Your Family First <span></span></h4>
                <div class="form">
                <%= form_for(Family.new, url: user_do_family_register_path , method: :post) do |f| %>
                    <%= f.text_field :family_name , class: "txt" , placeholder: "Please enter your family name" %>
                    <%= f.text_field :no_of_members , class: "txt" , placeholder: "Please enter your family name" %>
                    <%= f.submit "Register" , class: "txt2" %>
                <% end %>
            </div>
            </div>
            </div
	</div>
</div>


<style>
form_main {
    width: 100%;
}
.form_main h4 {
    font-family: roboto;
    font-size: 20px;
    font-weight: 300;
    margin-bottom: 15px;
    margin-top: 20px;
    text-transform: uppercase;
}
.heading {
    border-bottom: 1px solid #fcab0e;
    padding-bottom: 9px;
    position: relative;
}
.heading span {
    background: #9e6600 none repeat scroll 0 0;
    bottom: -2px;
    height: 3px;
    left: 0;
    position: absolute;
    width: 75px;
}   
.form {
    border-radius: 7px;
    padding: 6px;
}
.txt[type="text"] {
    border: 1px solid #ccc;
    margin: 10px 0;
    padding: 10px 0 10px 5px;
    width: 100%;
}
.txt_3[type="text"] {
    margin: 10px 0 0;
    padding: 10px 0 10px 5px;
    width: 100%;
}
.txt2[type="submit"] {
    background: #242424 none repeat scroll 0 0;
    border: 1px solid #4f5c04;
    border-radius: 25px;
    color: #fff;
    font-size: 16px;
    font-style: normal;
    line-height: 35px;
    margin: 10px 0;
    padding: 0;
    text-transform: uppercase;
    width: 30%;
}
.txt2:hover {
    background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
    color: #5793ef;
    transition: all 0.5s ease 0s;
}

</style>

app/views/user/unapproved_users.html.erb
<div class="ui container">
<br><br><br>

<div class="link_right">
<i class="icon cloud download"></i>
<%=
  link_to 'Export Users',
  user_verified_users_path(format: :xlsx)
%>
</div>
<div class="link_center"><strong>Total Unapproved Users: <%= @users.count %></strong></div>
<table class="ui compact celled definition table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Payment</th>
      <th>Status</th>
      <th>Notify</th>
      <th>Show</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |p| %>
    <tr>
    <% if p.first_name.present? %>
      <td><%=p.first_name%></td>
      <% else %>
      <td>-</td>
      <% end %>
      <td><%=p.email%></td>
      <% if p.payment == 1 %>
      <td><i class="icon check green"></i></td>
      <% else %>
      <td><i class="icon x icon red"></i></td>
      <% end %>

      <% if p.status == 1 %>
      <td><i class="icon check green"></i></td>
      <% else %>
      <td><i class="icon x icon red"></i></td>
      <% end %>


      <% if p.payment == 1 %>
      <td><%= button_to "Notify user" , user_send_regenerate_active_token_email_path(id: p.id) %></td>
      <% else %>
      <td><%= button_to "Notify user" ,  payments_track_send_payment_reminder_path(id: p.id) %></td>
     
      <% end %>


      <td><%= link_to "Show" , user_view_user_path(id: p.id) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <div class="ui right floated small labeled icon button">
          <i class="user icon"></i> <%= link_to "Add new user" %>
        </div>
        <div class="ui small button">
          <%= link_to "Back" , :back %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>
</div>


<script>

</script>

app/views/user/unpaid_users.html.erb
<div class="ui container">
<br><br><br>

<div class="link_center"><strong>Total Unpaid Users: <%= @users.count %></strong></div>
<table class="ui compact celled definition table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Payment</th>
      <th>Notify</th>
      <th>Show</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |p| %>
    <tr>
    <% if p.first_name.present? %>
      <td><%=p.first_name%></td>
      <% else %>
      <td>-</td>
      <% end %>
      <td><%=p.email%></td>
      <% if p.payment == 1 %>
      <td><i class="icon check green"></i></td>
      <% else %>
      <td><i class="icon x icon red"></i></td>
      <% end %>

      <% if p.payment == 1 %>
      <td><%= button_to "Notify user" , user_send_regenerate_active_token_email_path(id: p.id) %></td>
      <% else %>
      <td><%= button_to "Notify user" ,  payments_track_send_payment_reminder_path(id: p.id) %></td>
     
      <% end %>


      <td><%= link_to "Show" , user_view_user_path(id: p.id) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <div class="ui right floated small labeled icon button">
          <i class="user icon"></i> <%= link_to "Add new user" %>
        </div>
        <div class="ui small button">
          <%= link_to "Back" , :back %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>
</div>


<script>

</script>